"""
Daily history facts for Sigmoji — one entry per calendar day (366 total,
including Feb 29 for leap years).

Usage:
    from utils.categoryhistory import get_today_history
    fact = get_today_history()  # returns today's fact string
"""

from datetime import date

# Keys are (month, day) tuples.  Every calendar day is covered (366 entries).
DAILY_HISTORY: dict[tuple[int, int], str] = {
    # ── January ───────────────────────────────────────────────────────────────
    (1, 1):  "On this day in 45 BC, the Julian calendar took effect — the first calendar reform to add a leap day every four years.",
    (1, 2):  "In 1839, Louis Daguerre took the first photograph of the Moon, pioneering astrophotography.",
    (1, 3):  "In 1521, Martin Luther was excommunicated from the Catholic Church, igniting the Protestant Reformation.",
    (1, 4):  "In 2004, NASA's Spirit rover landed on Mars and began sending back stunning panoramic images.",
    (1, 5):  "In 1933, construction began on the Golden Gate Bridge, which would become an enduring icon of engineering.",
    (1, 6):  "In 1838, Samuel Morse first publicly demonstrated the electric telegraph, revolutionizing long-distance communication.",
    (1, 7):  "In 1610, Galileo discovered three of Jupiter's moons — Io, Europa, and Callisto — forever changing our view of the cosmos.",
    (1, 8):  "In 1889, Herman Hollerith patented the electric tabulating machine, a precursor to the modern computer.",
    (1, 9):  "In 2007, Steve Jobs unveiled the first iPhone, redefining smartphones and personal computing forever.",
    (1, 10): "In 1946, the first United Nations General Assembly convened in London with 51 member nations.",
    (1, 11): "In 1922, insulin was first administered to a diabetic patient, marking one of medicine's greatest breakthroughs.",
    (1, 12): "In 2010, a magnitude 7.0 earthquake struck Haiti, prompting an unprecedented global humanitarian response.",
    (1, 13): "In 1910, the first public radio broadcast featured live opera from the Metropolitan Opera House in New York.",
    (1, 14): "In 1953, Josip Broz Tito became the first president of Yugoslavia, shaping Cold War non-alignment.",
    (1, 15): "In 2001, Wikipedia launched, becoming the largest collaboratively edited reference work in history.",
    (1, 16): "In 1547, Ivan IV was crowned the first Tsar of Russia, beginning the Tsardom era.",
    (1, 17): "In 1773, Captain James Cook's ship became the first to cross the Antarctic Circle.",
    (1, 18): "In 1778, Captain Cook became the first European to reach the Hawaiian Islands.",
    (1, 19): "In 1983, Apple introduced the Lisa, one of the first personal computers with a graphical user interface.",
    (1, 20): "In 1961, John F. Kennedy was inaugurated and delivered his iconic 'Ask not what your country can do for you' speech.",
    (1, 21): "In 1976, the Concorde made its first commercial supersonic passenger flight, crossing the Atlantic in under 4 hours.",
    (1, 22): "In 1901, Queen Victoria died after 63 years on the throne, the longest reign in British history at that time.",
    (1, 23): "In 1849, Elizabeth Blackwell became the first woman to receive a medical degree in the United States.",
    (1, 24): "In 1848, James W. Marshall found gold at Sutter's Mill in California, sparking the Gold Rush.",
    (1, 25): "In 1961, President Kennedy held the first live televised presidential news conference.",
    (1, 26): "In 1788, the First Fleet arrived at Sydney Cove, marking the founding of modern Australia.",
    (1, 27): "In 1945, Soviet troops liberated the Auschwitz concentration camp — now remembered as International Holocaust Remembrance Day.",
    (1, 28): "In 1986, the Space Shuttle Challenger broke apart 73 seconds after launch, a defining moment in space exploration history.",
    (1, 29): "In 1886, Karl Benz patented the first true automobile powered by an internal combustion engine.",
    (1, 30): "In 1948, Mahatma Gandhi was assassinated, leaving behind a legacy of non-violent resistance that changed the world.",
    (1, 31): "In 1958, Explorer 1, the first U.S. satellite, launched into orbit and discovered the Van Allen radiation belts.",

    # ── February ──────────────────────────────────────────────────────────────
    (2, 1):  "In 2003, the Space Shuttle Columbia disintegrated upon re-entry, reminding the world of the risks of space exploration.",
    (2, 2):  "In 1887, Groundhog Day was celebrated for the first time in Punxsutawney, Pennsylvania.",
    (2, 3):  "In 1959, the 'Day the Music Died' — Buddy Holly, Ritchie Valens, and The Big Bopper perished in a plane crash.",
    (2, 4):  "In 2004, Mark Zuckerberg launched Facebook from his Harvard dorm room, beginning the social media revolution.",
    (2, 5):  "In 1919, Charlie Chaplin, Mary Pickford, Douglas Fairbanks, and D.W. Griffith founded United Artists studio.",
    (2, 6):  "In 1952, Elizabeth II became Queen of the United Kingdom at age 25, beginning a reign spanning seven decades.",
    (2, 7):  "In 1964, The Beatles arrived in New York for the first time, igniting the 'British Invasion' of American pop culture.",
    (2, 8):  "In 1865, Gregor Mendel presented his groundbreaking research on heredity in pea plants, founding modern genetics.",
    (2, 9):  "In 1971, Apollo 14 astronauts returned to Earth after the third successful Moon landing mission.",
    (2, 10): "In 1996, IBM's Deep Blue defeated chess champion Garry Kasparov in a game, a milestone in artificial intelligence.",
    (2, 11): "In 1990, Nelson Mandela was freed after 27 years in prison, paving the way for the end of apartheid.",
    (2, 12): "In 1809, Abraham Lincoln and Charles Darwin were both born, each destined to reshape their fields profoundly.",
    (2, 13): "In 1633, Galileo arrived in Rome for his trial before the Inquisition for advocating heliocentrism.",
    (2, 14): "In 1876, Alexander Graham Bell filed his patent for the telephone, just hours before a competing inventor.",
    (2, 15): "In 1965, Canada adopted the Maple Leaf flag, replacing the Red Ensign as the national symbol.",
    (2, 16): "In 1923, Howard Carter opened the burial chamber of King Tutankhamun in Egypt's Valley of the Kings.",
    (2, 17): "In 1867, the first ship passed through the Suez Canal, transforming global maritime trade routes.",
    (2, 18): "In 1930, Clyde Tombaugh discovered Pluto at Lowell Observatory, adding a ninth planet (later reclassified).",
    (2, 19): "In 1878, Thomas Edison patented the phonograph, the first device to record and reproduce sound.",
    (2, 20): "In 1962, John Glenn became the first American to orbit Earth aboard Friendship 7.",
    (2, 21): "In 1848, Karl Marx and Friedrich Engels published The Communist Manifesto, reshaping political thought worldwide.",
    (2, 22): "In 1997, scientists announced the birth of Dolly the sheep, the first mammal cloned from an adult cell.",
    (2, 23): "In 1455, the Gutenberg Bible, the first major book printed with movable type, was published in Mainz, Germany.",
    (2, 24): "In 1920, the Nazi Party was founded in Munich, a dark turning point in 20th century history.",
    (2, 25): "In 1870, Hiram Revels became the first African American to serve in the U.S. Senate.",
    (2, 26): "In 1935, Robert Watson-Watt first demonstrated radar, a technology that would prove decisive in WWII.",
    (2, 27): "In 1951, the 22nd Amendment to the U.S. Constitution was ratified, limiting presidents to two terms.",
    (2, 28): "In 1953, James Watson and Francis Crick announced they had discovered the double-helix structure of DNA.",
    (2, 29): "Leap Day — this date exists only once every four years, making anyone born today a rare 'leapling' who ages slowly on paper.",

    # ── March ─────────────────────────────────────────────────────────────────
    (3, 1):  "In 1872, Yellowstone became the world's first national park, setting a precedent for conservation worldwide.",
    (3, 2):  "In 1969, the Concorde made its maiden test flight from Toulouse, reaching Mach 2 for the first time.",
    (3, 3):  "In 1847, Alexander Graham Bell was born — he would later invent the telephone and transform communication.",
    (3, 4):  "In 1789, the U.S. Constitution went into effect as the first Congress met in New York City.",
    (3, 5):  "In 1953, Joseph Stalin died, ending 30 years of Soviet rule and ushering in the Khrushchev Thaw.",
    (3, 6):  "In 1899, Bayer registered 'Aspirin' as a trademark, introducing one of the most widely used medicines ever.",
    (3, 7):  "In 1876, Alexander Graham Bell was granted a patent for the telephone, changing human communication forever.",
    (3, 8):  "International Women's Day has been observed since 1911, celebrating women's social and political achievements.",
    (3, 9):  "In 1959, Barbie made her debut at the New York Toy Fair, becoming one of the most iconic toys in history.",
    (3, 10): "In 1876, Alexander Graham Bell made the first successful telephone call, saying 'Mr. Watson, come here.'",
    (3, 11): "In 2011, a massive earthquake and tsunami struck Japan, leading to the Fukushima nuclear disaster.",
    (3, 12): "In 1894, Coca-Cola was sold in bottles for the first time — previously only available at soda fountains.",
    (3, 13): "In 1781, William Herschel discovered Uranus, the first planet found with a telescope.",
    (3, 14): "Pi Day — March 14 (3/14) celebrates the mathematical constant π, also Albert Einstein's birthday (1879).",
    (3, 15): "In 44 BC, Julius Caesar was assassinated on the Ides of March, changing the course of Roman history.",
    (3, 16): "In 1926, Robert Goddard launched the world's first liquid-fueled rocket, pioneering modern rocketry.",
    (3, 17): "Saint Patrick's Day has been celebrated since the early 17th century, honoring Ireland's patron saint.",
    (3, 18): "In 1965, Alexei Leonov performed the first spacewalk, floating outside his spacecraft for 12 minutes.",
    (3, 19): "In 2003, the Iraq War began with airstrikes on Baghdad, launching a conflict that would last over a decade.",
    (3, 20): "The vernal equinox — day and night are nearly equal, marking the astronomical start of spring in the Northern Hemisphere.",
    (3, 21): "In 1963, Alcatraz Federal Penitentiary officially closed its doors after 29 years of housing notorious inmates.",
    (3, 22): "World Water Day, established in 1993, raises awareness about the 2 billion people living without safe drinking water.",
    (3, 23): "In 1839, the first recorded use of 'OK' appeared in the Boston Morning Post, and the word spread worldwide.",
    (3, 24): "In 1882, Robert Koch announced the discovery of the tuberculosis bacillus, winning the Nobel Prize for this work.",
    (3, 25): "In 1655, Christiaan Huygens discovered Titan, Saturn's largest moon, using a homemade 50-power telescope.",
    (3, 26): "In 1953, Jonas Salk announced his polio vaccine, one of the greatest medical achievements of the 20th century.",
    (3, 27): "In 1964, Alaska was struck by a magnitude 9.2 earthquake, the most powerful ever recorded in North America.",
    (3, 28): "In 1979, the Three Mile Island nuclear accident occurred, the worst in U.S. commercial nuclear power history.",
    (3, 29): "In 1886, John Pemberton brewed the first batch of Coca-Cola syrup in Atlanta, Georgia.",
    (3, 30): "In 1867, the U.S. purchased Alaska from Russia for $7.2 million — about 2 cents per acre.",
    (3, 31): "In 1889, the Eiffel Tower was inaugurated in Paris, standing as the world's tallest structure for 41 years.",

    # ── April ─────────────────────────────────────────────────────────────────
    (4, 1):  "April Fools' Day — the tradition of pranks on this day has been traced back to Chaucer's Canterbury Tales (1392).",
    (4, 2):  "In 1902, the first purpose-built movie theater, the Electric Theatre, opened in Los Angeles.",
    (4, 3):  "In 1973, the first handheld mobile phone call was made by Motorola's Martin Cooper in New York City.",
    (4, 4):  "In 1968, Martin Luther King Jr. was assassinated in Memphis, sparking mourning and civil rights reform worldwide.",
    (4, 5):  "In 1722, Jacob Roggeveen became the first European to discover Easter Island and its mysterious moai statues.",
    (4, 6):  "In 1896, the first modern Olympic Games opened in Athens, reviving an ancient tradition after 1,500 years.",
    (4, 7):  "In 1948, the World Health Organization was established, now observed annually as World Health Day.",
    (4, 8):  "In 1820, the Venus de Milo was discovered on the Greek island of Milos and is now the Louvre's most famous sculpture.",
    (4, 9):  "In 1865, General Robert E. Lee surrendered at Appomattox Court House, effectively ending the American Civil War.",
    (4, 10): "In 1912, the RMS Titanic set sail from Southampton on her maiden and only voyage.",
    (4, 11): "In 1970, Apollo 13 launched — 'Houston, we've had a problem' became one of space exploration's most famous phrases.",
    (4, 12): "In 1961, Yuri Gagarin became the first human in space, orbiting Earth aboard Vostok 1.",
    (4, 13): "In 1743, Thomas Jefferson was born — he would draft the Declaration of Independence and become the third U.S. president.",
    (4, 14): "In 1865, Abraham Lincoln was shot at Ford's Theatre; he died the next morning, the first U.S. president assassinated.",
    (4, 15): "In 1912, the Titanic sank after striking an iceberg, claiming over 1,500 lives in the deadliest peacetime maritime disaster.",
    (4, 16): "In 1867, Wilbur Wright was born — he and his brother Orville would achieve the first powered flight 36 years later.",
    (4, 17): "In 1961, the Bay of Pigs invasion began in Cuba, a failed CIA-backed operation that escalated Cold War tensions.",
    (4, 18): "In 1906, a devastating earthquake struck San Francisco, destroying over 80% of the city.",
    (4, 19): "In 1775, the Battles of Lexington and Concord marked the start of the American Revolutionary War.",
    (4, 20): "In 1902, Marie and Pierre Curie isolated radium, advancing our understanding of radioactivity.",
    (4, 21): "In 753 BC, according to legend, Romulus founded the city of Rome — the start of one of history's greatest civilizations.",
    (4, 22): "Earth Day, first celebrated in 1970, launched the modern environmental movement with 20 million participants.",
    (4, 23): "In 1564, William Shakespeare was born in Stratford-upon-Avon — he would become literature's most influential writer.",
    (4, 24): "In 1990, the Hubble Space Telescope was deployed from the Space Shuttle Discovery into Earth orbit.",
    (4, 25): "In 1953, Watson and Crick published their paper on the DNA double helix structure in the journal Nature.",
    (4, 26): "In 1986, the Chernobyl nuclear disaster occurred, the worst nuclear accident in history, contaminating vast areas of Europe.",
    (4, 27): "In 1791, Samuel Morse was born — he would co-invent the telegraph and develop Morse code.",
    (4, 28): "In 2001, Dennis Tito became the first space tourist, paying $20 million for a trip to the International Space Station.",
    (4, 29): "In 1945, Adolf Hitler married Eva Braun in his Berlin bunker, one day before both took their own lives.",
    (4, 30): "In 1789, George Washington was inaugurated as the first President of the United States in New York City.",

    # ── May ────────────────────────────────────────────────────────────────────
    (5, 1):  "In 1931, the Empire State Building opened in New York, standing as the world's tallest building for nearly 40 years.",
    (5, 2):  "In 2011, U.S. special forces carried out Operation Neptune Spear, tracking down Osama bin Laden in Abbottabad, Pakistan.",
    (5, 3):  "World Press Freedom Day, proclaimed in 1993, highlights the importance of a free and independent media.",
    (5, 4):  "Star Wars Day — 'May the Fourth be with you' celebrates the cultural phenomenon that began in 1977.",
    (5, 5):  "In 1961, Alan Shepard became the first American in space aboard Freedom 7 in a 15-minute suborbital flight.",
    (5, 6):  "In 1994, the Channel Tunnel opened, connecting England and France beneath the English Channel for the first time.",
    (5, 7):  "In 1824, Beethoven's Ninth Symphony premiered in Vienna — the composer was completely deaf by this time.",
    (5, 8):  "In 1886, Dr. John Pemberton served the first Coca-Cola at Jacobs' Pharmacy in Atlanta — it sold about 9 glasses per day.",
    (5, 9):  "In 1960, the FDA approved the first commercially produced birth control pill, transforming reproductive healthcare.",
    (5, 10): "In 1869, the First Transcontinental Railroad was completed at Promontory Summit, Utah, uniting America coast to coast.",
    (5, 11): "In 1997, IBM's Deep Blue defeated world chess champion Garry Kasparov in a full match — a watershed moment for AI.",
    (5, 12): "International Nurses Day honors Florence Nightingale's birthday (1820) and the contributions of nurses worldwide.",
    (5, 13): "In 1950, the first Formula One World Championship race was held at Silverstone, England.",
    (5, 14): "In 1796, Edward Jenner administered the first successful smallpox vaccination, pioneering immunology.",
    (5, 15): "In 1940, nylon stockings went on sale for the first time, with 4 million pairs sold in the first two days.",
    (5, 16): "In 1960, Theodore Maiman built the first working laser, opening doors to countless technologies we use today.",
    (5, 17): "In 1954, the U.S. Supreme Court ruled unanimously in Brown v. Board of Education that school segregation was unconstitutional.",
    (5, 18): "In 1980, Mount St. Helens erupted in Washington state, the deadliest volcanic event in U.S. history.",
    (5, 19): "In 1536, Anne Boleyn was beheaded at the Tower of London, the first English queen to be executed.",
    (5, 20): "In 1927, Charles Lindbergh took off on the first solo nonstop transatlantic flight from New York to Paris.",
    (5, 21): "In 1881, the American Red Cross was founded by Clara Barton, inspired by the International Red Cross in Switzerland.",
    (5, 22): "In 1906, the Wright brothers received a patent for their 'Flying Machine,' officially recognizing powered flight.",
    (5, 23): "In 1934, Bonnie and Clyde were ambushed and killed in Louisiana, ending their infamous crime spree.",
    (5, 24): "In 1844, Samuel Morse sent the first telegraph message, 'What hath God wrought,' from Washington to Baltimore.",
    (5, 25): "In 1977, Star Wars premiered in theaters, eventually becoming one of the most successful film franchises in history.",
    (5, 26): "In 1896, Charles Dow published the first edition of the Dow Jones Industrial Average, tracking 12 stocks.",
    (5, 27): "In 1937, the Golden Gate Bridge opened to pedestrians — approximately 200,000 people walked across on opening day.",
    (5, 28): "In 1937, Volkswagen was founded by the German Labour Front, later producing the iconic Beetle.",
    (5, 29): "In 1953, Edmund Hillary and Tenzing Norgay became the first confirmed climbers to summit Mount Everest.",
    (5, 30): "In 1431, Joan of Arc was burned at the stake in Rouen, France — she was canonized as a saint in 1920.",
    (5, 31): "In 1859, the Big Ben clock tower in London began keeping time, and its bell has rung almost continuously since.",

    # ── June ──────────────────────────────────────────────────────────────────
    (6, 1):  "In 2009, General Motors filed for bankruptcy, the largest industrial bankruptcy in U.S. history at the time.",
    (6, 2):  "In 1953, Queen Elizabeth II was crowned at Westminster Abbey in the first globally televised coronation.",
    (6, 3):  "In 1965, Ed White became the first American to walk in space during the Gemini 4 mission.",
    (6, 4):  "In 1989, the Tiananmen Square protests were violently suppressed in Beijing, an event that shaped modern geopolitics.",
    (6, 5):  "World Environment Day, established in 1972, encourages global awareness and action for the environment.",
    (6, 6):  "In 1944, D-Day: Allied forces stormed the beaches of Normandy, the largest seaborne invasion in history.",
    (6, 7):  "In 1975, Sony introduced the Betamax VCR, launching the home video revolution (and the format wars).",
    (6, 8):  "In 632 AD, Prophet Muhammad died in Medina, having unified the Arabian Peninsula under Islam.",
    (6, 9):  "In 1934, Donald Duck made his debut in the animated short The Wise Little Hen.",
    (6, 10): "In 1935, two recovering alcoholics founded Alcoholics Anonymous in Akron, Ohio, pioneering the 12-step program.",
    (6, 11): "In 1962, three prisoners escaped Alcatraz on a makeshift raft — they were never found, dead or alive.",
    (6, 12): "In 1942, Anne Frank received a diary for her 13th birthday, which would become one of the most widely read books.",
    (6, 13): "In 1983, Pioneer 10 crossed Neptune's orbit, becoming the first human-made object to travel beyond all known planets.",
    (6, 14): "In 1777, the Continental Congress adopted the Stars and Stripes as the American flag.",
    (6, 15): "In 1215, King John sealed the Magna Carta, laying the foundation for constitutional law and human rights.",
    (6, 16): "In 1963, Valentina Tereshkova became the first woman in space aboard Vostok 6, orbiting Earth 48 times.",
    (6, 17): "In 1972, five men were arrested for breaking into the Watergate complex, triggering the biggest political scandal in U.S. history.",
    (6, 18): "In 1983, Sally Ride became the first American woman in space aboard the Space Shuttle Challenger.",
    (6, 19): "Juneteenth commemorates June 19, 1865, when enslaved people in Texas learned of their freedom — two years after the Emancipation Proclamation.",
    (6, 20): "In 1782, the U.S. Congress adopted the Great Seal of the United States featuring the bald eagle.",
    (6, 21): "The summer solstice — the longest day of the year in the Northern Hemisphere, celebrated since ancient times at Stonehenge.",
    (6, 22): "In 1633, Galileo was forced to recant his support for heliocentrism, allegedly muttering 'And yet it moves.'",
    (6, 23): "In 1868, Christopher Latham Sholes patented the typewriter, giving rise to the QWERTY keyboard layout we still use.",
    (6, 24): "In 1497, John Cabot reached North America (likely Newfoundland), the first European to do so since the Vikings.",
    (6, 25): "In 1876, the Battle of the Little Bighorn took place — Sitting Bull and Crazy Horse defeated General Custer.",
    (6, 26): "In 1945, the United Nations Charter was signed in San Francisco by representatives of 50 countries.",
    (6, 27): "In 1967, the world's first ATM was installed at a branch of Barclays Bank in London.",
    (6, 28): "In 1914, Archduke Franz Ferdinand was assassinated in Sarajevo, triggering a chain of events leading to World War I.",
    (6, 29): "In 2007, the first iPhone went on sale, with people camping outside Apple Stores for days to be among the first buyers.",
    (6, 30): "In 1971, the crew of the Soviet Soyuz 11 tragically died during re-entry — the only humans to have died in space itself.",

    # ── July ──────────────────────────────────────────────────────────────────
    (7, 1):  "In 1867, Canada became a self-governing dominion through Confederation, now celebrated as Canada Day.",
    (7, 2):  "In 1937, Amelia Earhart disappeared over the Pacific Ocean during her attempt to circumnavigate the globe.",
    (7, 3):  "In 1886, Karl Benz drove his Motorwagen in Mannheim, the first publicly demonstrated automobile ride.",
    (7, 4):  "In 1776, the Declaration of Independence was adopted, proclaiming American sovereignty from Britain.",
    (7, 5):  "In 1996, Dolly the sheep was born — the first mammal cloned from an adult somatic cell.",
    (7, 6):  "In 1885, Louis Pasteur successfully tested his rabies vaccine on a boy bitten by a rabid dog.",
    (7, 7):  "In 2005, a series of coordinated bombings struck London's transport system, killing 52 people.",
    (7, 8):  "In 1497, Vasco da Gama set sail from Lisbon, eventually reaching India and opening a sea route to Asia.",
    (7, 9):  "In 1877, the first Wimbledon Championship was held, making it the oldest tennis tournament in the world.",
    (7, 10): "In 1962, Telstar 1 was launched, the first active communications satellite to relay TV signals across the Atlantic.",
    (7, 11): "In 1979, Skylab, America's first space station, re-entered Earth's atmosphere, scattering debris across Australia.",
    (7, 12): "In 1862, the Medal of Honor was authorized by the U.S. Congress, the nation's highest military decoration.",
    (7, 13): "In 1985, the Live Aid concerts in London and Philadelphia raised over $125 million for famine relief in Ethiopia.",
    (7, 14): "In 1789, the storming of the Bastille in Paris ignited the French Revolution and became France's national day.",
    (7, 15): "In 1799, the Rosetta Stone was discovered in Egypt, providing the key to deciphering ancient hieroglyphics.",
    (7, 16): "In 1945, the Trinity test — the world's first nuclear detonation — took place in New Mexico.",
    (7, 17): "In 1955, Disneyland opened in Anaheim, California, Walt Disney's dream of the 'Happiest Place on Earth.'",
    (7, 18): "In 1925, Adolf Hitler published Mein Kampf, outlining the ideology that would lead to WWII and the Holocaust.",
    (7, 19): "In 1799, the Rosetta Stone was found by French soldiers in Egypt, unlocking the mystery of hieroglyphics.",
    (7, 20): "In 1969, Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon during Apollo 11.",
    (7, 21): "In 1969, Neil Armstrong spoke the immortal words: 'That's one small step for man, one giant leap for mankind.'",
    (7, 22): "In 1934, FBI agents shot and killed John Dillinger outside a Chicago theater, ending 'Public Enemy No. 1.'",
    (7, 23): "In 1829, William Austin Burt patented the typographer, an early forerunner of the modern typewriter.",
    (7, 24): "In 1911, American archaeologist Hiram Bingham rediscovered Machu Picchu high in the Peruvian Andes.",
    (7, 25): "In 1978, the world's first test-tube baby, Louise Brown, was born via in vitro fertilization in England.",
    (7, 26): "In 1947, President Truman signed the National Security Act, creating the CIA and restructuring U.S. defense.",
    (7, 27): "In 1940, Bugs Bunny made his debut in the animated short A Wild Hare, asking 'What's up, Doc?'",
    (7, 28): "In 1914, Austria-Hungary declared war on Serbia, officially beginning World War I.",
    (7, 29): "In 1958, NASA was established by President Eisenhower, launching the era of American space exploration.",
    (7, 30): "In 1619, the first representative assembly in America convened in Jamestown, Virginia.",
    (7, 31): "In 1790, the U.S. Patent Office issued its first patent, for a process of making potash (a fertilizer ingredient).",

    # ── August ────────────────────────────────────────────────────────────────
    (8, 1):  "In 1981, MTV launched with the music video 'Video Killed the Radio Star,' revolutionizing the music industry.",
    (8, 2):  "In 1990, Iraq invaded Kuwait, triggering the Gulf War and a massive international coalition response.",
    (8, 3):  "In 2004, NASA's Messenger spacecraft launched toward Mercury, becoming the first to orbit the innermost planet.",
    (8, 4):  "In 1693, Dom Pérignon is said to have developed the method for making Champagne, though the story is likely legend.",
    (8, 5):  "In 1858, the first transatlantic telegraph cable was completed, linking Europe and North America for instant communication.",
    (8, 6):  "In 1945, the atomic bomb 'Little Boy' was dropped on Hiroshima, the first use of nuclear weapons in warfare.",
    (8, 7):  "In 1959, Explorer 6 transmitted the first photograph of Earth from orbit, a grainy but historic image.",
    (8, 8):  "In 1963, the Great Train Robbery took place in England — thieves stole £2.6 million (about £58 million today).",
    (8, 9):  "In 1945, the atomic bomb 'Fat Man' was dropped on Nagasaki, hastening Japan's surrender and the end of WWII.",
    (8, 10): "In 1675, King Charles II laid the foundation stone of the Royal Observatory at Greenwich, home of the Prime Meridian.",
    (8, 11): "In 1999, the last total solar eclipse of the millennium was visible across Europe, drawing millions of observers.",
    (8, 12): "In 1877, Thomas Edison completed the first phonograph and tested it by reciting 'Mary Had a Little Lamb.'",
    (8, 13): "In 1961, construction of the Berlin Wall began overnight, dividing East and West Berlin for 28 years.",
    (8, 14): "In 1935, the Social Security Act was signed into law, creating the American social safety net.",
    (8, 15): "In 1945, Japan announced its surrender, effectively ending World War II — celebrated as V-J Day.",
    (8, 16): "In 1858, Queen Victoria and President Buchanan exchanged the first transatlantic telegraph messages.",
    (8, 17): "In 1978, the Double Eagle II completed the first transatlantic crossing by hot air balloon.",
    (8, 18): "In 1920, the 19th Amendment was ratified, granting women the right to vote in the United States.",
    (8, 19): "In 1839, the French government announced the daguerreotype process, making photography available to the public.",
    (8, 20): "In 1977, Voyager 2 launched from Cape Canaveral, beginning its grand tour of the outer solar system.",
    (8, 21): "In 1959, Hawaii became the 50th U.S. state, the most recent addition to the union.",
    (8, 22): "In 1902, Theodore Roosevelt became the first U.S. president to ride in an automobile.",
    (8, 23): "In 1966, the first photograph of Earth from lunar orbit was taken by Lunar Orbiter 1.",
    (8, 24): "In 79 AD, Mount Vesuvius erupted, burying Pompeii and Herculaneum and preserving them for millennia.",
    (8, 25): "In 1835, the 'Great Moon Hoax' articles in the New York Sun claimed life had been found on the Moon.",
    (8, 26): "In 1920, women in the U.S. voted for the first time after the 19th Amendment was certified.",
    (8, 27): "In 1883, Krakatoa erupted with a force of 200 megatons of TNT, heard 4,800 km away — the loudest sound in recorded history.",
    (8, 28): "In 1963, Martin Luther King Jr. delivered his 'I Have a Dream' speech to 250,000 people at the Lincoln Memorial.",
    (8, 29): "In 2005, Hurricane Katrina made landfall on the Gulf Coast, one of the costliest natural disasters in U.S. history.",
    (8, 30): "In 1963, the Washington-Moscow hotline ('red telephone') became operational, aiming to prevent accidental nuclear war.",
    (8, 31): "In 1997, Princess Diana was killed in a car crash in Paris, triggering an unprecedented outpouring of global grief.",

    # ── September ─────────────────────────────────────────────────────────────
    (9, 1):  "In 1939, Germany invaded Poland, marking the beginning of World War II in Europe.",
    (9, 2):  "In 1945, Japan formally surrendered aboard the USS Missouri in Tokyo Bay, officially ending World War II.",
    (9, 3):  "In 1783, the Treaty of Paris was signed, formally ending the American Revolutionary War.",
    (9, 4):  "In 1998, Google was incorporated by Larry Page and Sergey Brin in a friend's garage in Menlo Park.",
    (9, 5):  "In 1977, Voyager 1 launched, now the most distant human-made object — over 15 billion miles from Earth.",
    (9, 6):  "In 1620, the Mayflower departed from Plymouth, England, carrying 102 passengers to the New World.",
    (9, 7):  "In 1936, the last known thylacine (Tasmanian tiger) died at the Hobart Zoo, marking the species' extinction.",
    (9, 8):  "In 1966, Star Trek premiered on NBC, introducing a fictional universe that inspired generations of scientists.",
    (9, 9):  "In 1947, the first computer 'bug' — a real moth — was found trapped in a Harvard Mark II relay.",
    (9, 10): "In 2008, the Large Hadron Collider at CERN was first powered up, the most complex machine ever built.",
    (9, 11): "In 2001, terrorist attacks on the World Trade Center and Pentagon killed nearly 3,000 people, reshaping global security.",
    (9, 12): "In 1940, four teenagers discovered the Lascaux cave paintings in France, art created over 17,000 years ago.",
    (9, 13): "In 1959, the Soviet Luna 2 became the first human-made object to reach the surface of the Moon.",
    (9, 14): "In 1752, Britain adopted the Gregorian calendar, skipping 11 days — people went to bed Sept 2 and woke up Sept 14.",
    (9, 15): "In 2008, Lehman Brothers filed for bankruptcy, triggering the worst global financial crisis since the Great Depression.",
    (9, 16): "In 1620, the Mayflower set sail from Plymouth, England, beginning its historic voyage to the New World.",
    (9, 17): "In 1787, the U.S. Constitution was signed by 39 delegates at the Constitutional Convention in Philadelphia.",
    (9, 18): "In 1947, the U.S. Air Force was established as an independent military branch, separate from the Army.",
    (9, 19): "In 1991, Ötzi the Iceman was discovered in the Alps — a 5,300-year-old natural mummy in remarkably preserved condition.",
    (9, 20): "In 1519, Ferdinand Magellan set sail from Spain with five ships, beginning the first circumnavigation of the Earth.",
    (9, 21): "International Day of Peace, established by the UN in 1981, calls for a global ceasefire and non-violence.",
    (9, 22): "In 1862, Abraham Lincoln issued the Emancipation Proclamation, declaring all enslaved people in rebel states 'shall be free.'",
    (9, 23): "In 1846, Johann Galle discovered Neptune, the eighth planet, using mathematical predictions by Le Verrier.",
    (9, 24): "In 1957, President Eisenhower sent federal troops to Little Rock, Arkansas, to enforce school desegregation.",
    (9, 25): "In 1513, Vasco Núñez de Balboa became the first European to see the Pacific Ocean from the Americas.",
    (9, 26): "In 1960, the first televised U.S. presidential debate between Kennedy and Nixon changed political campaigns forever.",
    (9, 27): "In 1905, Albert Einstein published his paper introducing E=mc², the most famous equation in physics.",
    (9, 28): "In 1928, Alexander Fleming discovered penicillin by accident, launching the age of antibiotics.",
    (9, 29): "In 1829, London's Metropolitan Police force was established by Sir Robert Peel — officers were nicknamed 'Bobbies.'",
    (9, 30): "In 1955, James Dean died in a car crash at age 24, becoming a lasting symbol of youthful rebellion.",

    # ── October ───────────────────────────────────────────────────────────────
    (10, 1):  "In 1908, the Ford Model T went on sale, the first affordable automobile that put America on wheels.",
    (10, 2):  "In 1950, the comic strip Peanuts by Charles Schulz debuted, introducing Charlie Brown and Snoopy to the world.",
    (10, 3):  "In 1990, East and West Germany were reunified after 45 years of division, ending the Cold War's most visible symbol.",
    (10, 4):  "In 1957, the Soviet Union launched Sputnik 1, the first artificial satellite, igniting the Space Race.",
    (10, 5):  "In 1947, President Truman made the first televised presidential address from the White House.",
    (10, 6):  "In 1927, The Jazz Singer premiered, the first feature-length 'talkie' with synchronized dialogue.",
    (10, 7):  "In 2001, the U.S. military began operations in Afghanistan in response to the September 11 attacks.",
    (10, 8):  "In 1871, the Great Chicago Fire broke out, destroying 3.3 square miles and leaving 100,000 people homeless.",
    (10, 9):  "In 1874, the Universal Postal Union was established, making international mail delivery efficient and affordable.",
    (10, 10): "In 1913, President Wilson triggered the dynamite blast that completed the Panama Canal, connecting two oceans.",
    (10, 11): "In 1975, Saturday Night Live premiered on NBC, becoming the longest-running sketch comedy show in TV history.",
    (10, 12): "In 1492, Christopher Columbus's expedition first sighted land in the Americas — an island in the Bahamas.",
    (10, 13): "In 1792, the cornerstone of the White House was laid, beginning construction of the future presidential residence.",
    (10, 14): "In 1947, Chuck Yeager broke the sound barrier flying the Bell X-1 at Mach 1.06 over the Mojave Desert.",
    (10, 15): "In 1878, the Edison Electric Light Company began operations, bringing electric illumination to the world.",
    (10, 16): "In 1923, Walt and Roy Disney founded the Disney Brothers Cartoon Studio, the precursor to The Walt Disney Company.",
    (10, 17): "In 1979, Mother Teresa was awarded the Nobel Peace Prize for her humanitarian work in Calcutta's slums.",
    (10, 18): "In 1867, the U.S. formally took possession of Alaska from Russia in a ceremony at Sitka.",
    (10, 19): "In 1781, the British surrendered at Yorktown, the last major battle of the American Revolutionary War.",
    (10, 20): "In 1973, the Sydney Opera House was officially opened by Queen Elizabeth II after 16 years of construction.",
    (10, 21): "In 1879, Thomas Edison successfully tested a carbon-filament light bulb that burned for over 13 hours.",
    (10, 22): "In 1797, André-Jacques Garnerin made the first parachute jump from a balloon at 3,000 feet over Paris.",
    (10, 23): "In 4004 BC (traditionally), Bishop Ussher calculated the world was created — the date became a famous chronological reference.",
    (10, 24): "In 1945, the United Nations officially came into existence when its Charter was ratified by the five permanent Security Council members.",
    (10, 25): "In 1854, the Charge of the Light Brigade occurred during the Crimean War, immortalized by Tennyson's poem.",
    (10, 26): "In 1881, the Gunfight at the O.K. Corral took place in Tombstone, Arizona — it lasted only 30 seconds.",
    (10, 27): "In 1904, the New York City subway opened with its first line, now one of the world's busiest transit systems.",
    (10, 28): "In 1886, the Statue of Liberty was dedicated in New York Harbor, a gift from France symbolizing freedom.",
    (10, 29): "In 1929, the stock market crashed on 'Black Tuesday,' triggering the Great Depression.",
    (10, 30): "In 1938, Orson Welles' War of the Worlds radio broadcast caused widespread panic — listeners thought Martians had invaded.",
    (10, 31): "In 1517, Martin Luther posted his 95 Theses on the door of a church in Wittenberg, sparking the Reformation.",

    # ── November ──────────────────────────────────────────────────────────────
    (11, 1):  "In 1512, Michelangelo's Sistine Chapel ceiling paintings were first exhibited to the public — four years of work lying on his back.",
    (11, 2):  "In 2000, the first permanent crew arrived at the International Space Station, beginning continuous human habitation in orbit.",
    (11, 3):  "In 1957, the Soviet Union launched Sputnik 2 with Laika the dog, the first living creature to orbit Earth.",
    (11, 4):  "In 1922, Howard Carter discovered the entrance to King Tutankhamun's tomb in Egypt's Valley of the Kings.",
    (11, 5):  "In 1605, the Gunpowder Plot to blow up the English Parliament was foiled — now celebrated as Guy Fawkes Night.",
    (11, 6):  "In 1860, Abraham Lincoln was elected the 16th President of the United States, leading to Southern secession.",
    (11, 7):  "In 1917, the Bolshevik Revolution began in Russia, overthrowing the provisional government and establishing Soviet power.",
    (11, 8):  "In 1895, Wilhelm Röntgen accidentally discovered X-rays while experimenting with cathode rays in his lab.",
    (11, 9):  "In 1989, the Berlin Wall fell as East Germany opened its borders, symbolizing the end of the Cold War.",
    (11, 10): "In 1871, Henry Morton Stanley found missing explorer David Livingstone in Africa, greeting him with 'Dr. Livingstone, I presume?'",
    (11, 11): "In 1918, World War I ended with the Armistice at the 11th hour of the 11th day of the 11th month.",
    (11, 12): "In 1990, Tim Berners-Lee published a formal proposal for the World Wide Web, changing civilization forever.",
    (11, 13): "In 2015, terrorist attacks in Paris killed 130 people, the deadliest attack on French soil since World War II.",
    (11, 14): "In 1889, journalist Nellie Bly set off to beat Jules Verne's fictional 80-day trip around the world — she did it in 72.",
    (11, 15): "In 1971, Intel released the 4004, the world's first commercial microprocessor, launching the personal computing revolution.",
    (11, 16): "In 1945, UNESCO was founded to promote international cooperation in education, science, and culture.",
    (11, 17): "In 1869, the Suez Canal officially opened, dramatically shortening the sea route between Europe and Asia.",
    (11, 18): "In 1928, Mickey Mouse made his debut in Steamboat Willie, the first cartoon with synchronized sound throughout.",
    (11, 19): "In 1863, Abraham Lincoln delivered the Gettysburg Address, a 272-word speech that became a cornerstone of American democracy.",
    (11, 20): "In 1945, the Nuremberg Trials began, the first international war crimes tribunal in history.",
    (11, 21): "In 1877, Thomas Edison announced the phonograph, his favorite invention, capable of recording and playing back sound.",
    (11, 22): "In 1963, President John F. Kennedy was assassinated in Dallas, Texas, a moment that shook the entire world.",
    (11, 23): "In 1936, the first issue of Life magazine was published, pioneering photojournalism for the American public.",
    (11, 24): "In 1859, Charles Darwin published On the Origin of Species, introducing the theory of evolution by natural selection.",
    (11, 25): "In 1915, Albert Einstein presented the field equations of general relativity, revolutionizing our understanding of gravity.",
    (11, 26): "In 1922, Howard Carter peered into Tutankhamun's tomb and described seeing 'wonderful things' in the flickering candlelight.",
    (11, 27): "In 1978, Harvey Milk, the first openly gay elected official in California, was assassinated at San Francisco City Hall.",
    (11, 28): "In 1520, Ferdinand Magellan's fleet entered the Pacific Ocean after navigating the strait that now bears his name.",
    (11, 29): "In 1877, Thomas Edison demonstrated the hand-cranked phonograph for the first time, playing 'Mary Had a Little Lamb.'",
    (11, 30): "In 1872, the first international football (soccer) match was played between Scotland and England in Glasgow.",

    # ── December ──────────────────────────────────────────────────────────────
    (12, 1):  "In 1913, Ford's Highland Park assembly line began producing Model T's, reducing build time from 12 hours to 93 minutes.",
    (12, 2):  "In 1942, Enrico Fermi achieved the first self-sustaining nuclear chain reaction at the University of Chicago.",
    (12, 3):  "In 1967, the first human heart transplant was performed by Dr. Christiaan Barnard in Cape Town, South Africa.",
    (12, 4):  "In 1954, the first Burger King restaurant opened in Miami, Florida.",
    (12, 5):  "In 1933, Prohibition ended in the United States when the 21st Amendment was ratified.",
    (12, 6):  "In 1865, the 13th Amendment was ratified, permanently abolishing slavery throughout the United States.",
    (12, 7):  "In 1941, Japan attacked Pearl Harbor, killing 2,403 Americans and drawing the U.S. into World War II.",
    (12, 8):  "In 1980, John Lennon was shot and killed in New York City, silencing one of music's most influential voices.",
    (12, 9):  "In 1979, the World Health Organization certified the global eradication of smallpox, humanity's greatest medical triumph.",
    (12, 10): "In 1901, the first Nobel Prizes were awarded in Stockholm, honoring achievements in physics, chemistry, medicine, literature, and peace.",
    (12, 11): "In 1972, Apollo 17 astronauts became the last humans to walk on the Moon — no one has returned since.",
    (12, 12): "In 1901, Guglielmo Marconi received the first transatlantic radio signal, sent from Cornwall to Newfoundland.",
    (12, 13): "In 1577, Sir Francis Drake set sail from Plymouth on his circumnavigation of the globe, the first by an Englishman.",
    (12, 14): "In 1911, Roald Amundsen's expedition became the first to reach the South Pole, beating Robert Scott by 34 days.",
    (12, 15): "In 1939, Gone with the Wind premiered in Atlanta, becoming one of the highest-grossing films of all time.",
    (12, 16): "In 1773, the Boston Tea Party took place — colonists dumped 342 chests of tea into the harbor to protest taxation.",
    (12, 17): "In 1903, the Wright brothers achieved the first powered, sustained, and controlled airplane flight at Kitty Hawk.",
    (12, 18): "In 1865, the 13th Amendment was officially proclaimed, abolishing slavery throughout the United States.",
    (12, 19): "In 1843, Charles Dickens published A Christmas Carol, which revived and shaped modern Christmas traditions.",
    (12, 20): "In 1860, South Carolina became the first state to secede from the Union, setting the stage for the Civil War.",
    (12, 21): "The winter solstice — the shortest day of the year in the Northern Hemisphere, marking the astronomical start of winter.",
    (12, 22): "In 1849, Fyodor Dostoevsky was led before a firing squad, only to receive a last-second reprieve — the experience transformed his writing.",
    (12, 23): "In 1947, Bell Labs demonstrated the transistor, a tiny invention that enabled everything from smartphones to supercomputers.",
    (12, 24): "In 1968, Apollo 8 astronauts became the first humans to orbit the Moon, reading from Genesis on Christmas Eve.",
    (12, 25): "In 1991, Mikhail Gorbachev resigned as Soviet President, and the Soviet Union officially dissolved the next day.",
    (12, 26): "In 2004, a massive tsunami struck the Indian Ocean, killing over 230,000 people in 14 countries.",
    (12, 27): "In 1831, Charles Darwin set sail on HMS Beagle, a voyage that would inspire his theory of evolution.",
    (12, 28): "In 1895, the Lumière brothers held the first public film screening in Paris, giving birth to cinema.",
    (12, 29): "In 1170, Thomas Becket, Archbishop of Canterbury, was murdered in his own cathedral by knights loyal to King Henry II.",
    (12, 30): "In 1922, the Union of Soviet Socialist Republics was officially established, creating the world's first communist state.",
    (12, 31): "In 1879, Thomas Edison publicly demonstrated his incandescent light bulb for the first time at Menlo Park, New Jersey.",
}


def get_today_history(today: date | None = None) -> str:
    """Return today's historical fact. Falls back to a generic message if the date
    is somehow missing from the dictionary (shouldn't happen)."""
    if today is None:
        today = date.today()
    key = (today.month, today.day)
    return DAILY_HISTORY.get(key, "Every day is a chance to make history — go create something remarkable!")
